ALTER TABLE 학생 ADD 성별 CHAR(1);
ALTER TABLE 학생 MODIFY COLUMN 성별 VARCHAR(2);
ALTER TABLE 학생 CHANGE COLUMN 연락처 휴대폰번호 VARCHAR(20);
SELECT * FROM 학생;


ALTER TABLE 학생 DROP COLUMN 성별;
SELECT * FROM 학생;


ALTER TABLE 휴학생 RENAME 졸업생;


DROP TABLE 학과;
DROP TABLE 학생;


